# Generated by Django 5.0.6 on 2024-07-04 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='is_stuff',
            new_name='is_staff',
        ),
    ]
