# Generated by Django 5.0.6 on 2024-07-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('descriptions', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category')),
            ],
        ),
    ]
