# Generated by Django 5.0.6 on 2024-07-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_is_active_cart'),
        ('store', '0004_rename_catrgory_variations_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='variations',
            field=models.ManyToManyField(to='store.variations'),
        ),
    ]
