# Generated by Django 5.0.6 on 2024-07-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_variations'),
        ('store', '0004_rename_catrgory_variations_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.variations'),
        ),
    ]
